version: 2 
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 6f:95:78:01:b6:31:da:8d:49:7b:61:f7:a7:cf:7b:14
      - run:
          name: ssh
          command: |
            ssh -p $SSH_PORT $SSH_USER@$SSH_HOST
      - run:
          name: update
          command: |
            cd /home/ec2-user/bankbank/
            git pull
            cp /home/ec2-user/application.properties /home/ec2-user/bankbank/src/main/resources
            cp /home/ec2-user/bankbank/target/bankbank.jar /home/ec2-user
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master