version: 2 
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 6f:95:78:01:b6:31:da:8d:49:7b:61:f7:a7:cf:7b:14
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST
      - run:
          command: |
          cd /home/ec2-user/bankbank/
          git pull
          cp /home/ec2-user/application.properties /home/ec2-user/bankbank/src/main/resources
          cp /home/ec2-user/bankbank/target/bankbank.jar /home/ec2-user
      - add_ssh_keys:
          fingerprints:
            - d6:60:c9:6a:0a:2b:e4:b5:0b:68:9c:cf:77:fa:2c:20
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST_1c "/home/ec2-user/bankbank/deploy-me.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master