version: 2 
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 6f:95:78:01:b6:31:da:8d:49:7b:61:f7:a7:cf:7b:14
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/home/ec2-user/bankbank/deploy-me.sh"
      - run: mvn clean dependency:copy-dependencies -DoutputDirectory=lib antrun:run package
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/home/ec2-user/bankbank/deploy-me2.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master