version: 2 
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - 6f:95:78:01:b6:31:da:8d:49:7b:61:f7:a7:cf:7b:14
      - run: sudo apt-get install maven
      - run:
          name: 1a
          command: |
            ssh -p $SSH_PORT $SSH_USER@$SSH_HOST '
            cd /home/ec2-user/bankbank/ &&
            git pull &&
            cp /home/ec2-user/application.properties /home/ec2-user/bankbank/src/main/resources &&
            mvn clean dependency:copy-dependencies -DoutputDirectory=lib antrun:run package &&
            cp /home/ec2-user/bankbank/target/bankbank.jar /home/ec2-user
            '
      - add_ssh_keys:
          fingerprints:
            - d6:60:c9:6a:0a:2b:e4:b5:0b:68:9c:cf:77:fa:2c:20
      - run: sudo apt-get install maven
      - run:
          name: 1c
          command: |
            ssh -p $SSH_PORT $SSH_USER@$SSH_HOST_1c '
            cd /home/ec2-user/bankbank/ &&
            git pull &&
            cp /home/ec2-user/application.properties /home/ec2-user/bankbank/src/main/resources &&
            mvn clean dependency:copy-dependencies -DoutputDirectory=lib antrun:run package &&
            cp /home/ec2-user/bankbank/target/bankbank.jar /home/ec2-user
            '
workflows:
  orbs:
    maven: circleci/maven@0.0.12
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master