version: 2 # CircleCI 2.0 を使用します
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - $FINGERPRINTS
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/home/ec2-user/bankbank/deploy-me.sh"
workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master